
-- Eliminar tablas existentes 

drop table if exists historial_incidente cascade;
drop table if exists alerta cascade;
drop table if exists asignacion_personal cascade;
drop table if exists asignacion_recurso cascade;
drop table if exists recurso cascade;
drop table if exists refugio cascade;
drop table if exists incidente cascade;
drop table if exists zona cascade;
drop table if exists usuario cascade;

drop function if exists sp_listar_usuarios() cascade;
drop function if exists sp_buscar_usuario(bigint) cascade;
drop function if exists sp_listar_zonas() cascade;
drop function if exists sp_buscar_zona(bigint) cascade;
drop function if exists sp_listar_incidentes() cascade;
drop function if exists sp_buscar_incidente(bigint) cascade;
drop function if exists sp_listar_refugios() cascade;
drop function if exists sp_buscar_refugio(bigint) cascade;
drop function if exists sp_listar_recursos() cascade;
drop function if exists sp_buscar_recurso(bigint) cascade;
drop function if exists sp_listar_asignaciones_recurso() cascade;
drop function if exists sp_buscar_asignacion_recurso(bigint) cascade;
drop function if exists sp_listar_asignaciones_personal() cascade;
drop function if exists sp_buscar_asignacion_personal(bigint) cascade;
drop function if exists sp_listar_alertas() cascade;
drop function if exists sp_buscar_alerta(bigint) cascade;
drop function if exists sp_listar_historial_incidente(bigint) cascade;
drop function if exists sp_buscar_historial_por_id(bigint) cascade;

-- tabla usuario
create table usuario (
    id bigint generated by default as identity primary key,
    nombre varchar(120) not null,
    email varchar(160) not null unique,
    password_hash varchar(255) not null,
    telefono varchar(30),
    rol varchar(30) not null default 'VOLUNTARIO'
        check (rol in ('ADMIN', 'COORDINADOR', 'RESCATISTA', 'VOLUNTARIO', 'GESTOR_REFUGIO')),
    activo boolean not null default true,
    habilidades text,
    disponible boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

-- tabla zona
create table zona (
    id bigint generated by default as identity primary key,
    nombre varchar(120) not null,
    municipio varchar(120),
    departamento varchar(120),
    pais varchar(80) not null default 'Guatemala',
    latitud numeric(9,6),
    longitud numeric(9,6),
    nivel_riesgo varchar(20) not null default 'MEDIO'
        check (nivel_riesgo in ('BAJO', 'MEDIO', 'ALTO', 'CRITICO')),
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

-- tabla incidente
create table incidente (
    id bigint generated by default as identity primary key,
    tipo varchar(40) not null
        check (tipo in ('INUNDACION', 'TERREMOTO', 'INCENDIO', 'DESLIZAMIENTO', 'ACTIVIDAD_VOLCANICA', 'OTRO')),
    titulo varchar(160) not null,
    descripcion text,
    nivel_emergencia varchar(20) not null default 'MEDIA'
        check (nivel_emergencia in ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    estado varchar(30) not null default 'REPORTADO'
        check (estado in ('REPORTADO', 'EN_ATENCION', 'MITIGADO', 'CERRADO')),
    fecha_reporte timestamptz not null default now(),
    fecha_cierre timestamptz,
    zona_id bigint not null references zona(id),
    reportado_por bigint not null references usuario(id),
    latitud numeric(9,6),
    longitud numeric(9,6),
    cantidad_personas_afectadas integer check (cantidad_personas_afectadas >= 0),
    observaciones text,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

-- tabla refugio
create table refugio (
    id bigint generated by default as identity primary key,
    nombre varchar(160) not null,
    direccion text,
    zona_id bigint references zona(id),
    latitud numeric(9,6),
    longitud numeric(9,6),
    capacidad_total integer not null check (capacidad_total >= 0),
    ocupacion_actual integer not null default 0 check (ocupacion_actual >= 0),
    estado varchar(20) not null default 'DISPONIBLE'
        check (estado in ('DISPONIBLE', 'PARCIAL', 'LLENO', 'INACTIVO')),
    responsable_id bigint references usuario(id),
    telefono_contacto varchar(30),
    observaciones text,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    constraint refugio_ocupacion_max check (ocupacion_actual <= capacidad_total)
);

-- tabla recurso
create table recurso (
    id bigint generated by default as identity primary key,
    nombre varchar(120) not null,
    tipo varchar(30) not null
        check (tipo in ('AGUA', 'ALIMENTO', 'MEDICAMENTO', 'EQUIPO', 'VEHICULO', 'OTRO')),
    unidad_medida varchar(30) not null default 'UNIDAD'
        check (unidad_medida in ('UNIDAD', 'CAJA', 'KILOGRAMO', 'LITRO', 'PERSONA', 'OTRO')),
    cantidad_total integer not null default 0 check (cantidad_total >= 0),
    descripcion text,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

-- tabla asignacion_recurso
create table asignacion_recurso (
    id bigint generated by default as identity primary key,
    recurso_id bigint not null references recurso(id),
    incidente_id bigint references incidente(id),
    refugio_id bigint references refugio(id),
    cantidad integer not null check (cantidad > 0),
    estado varchar(30) not null default 'SOLICITADO'
        check (estado in ('SOLICITADO', 'ASIGNADO', 'ENVIADO', 'ENTREGADO', 'CANCELADO')),
    fecha_solicitud timestamptz not null default now(),
    fecha_asignacion timestamptz,
    fecha_entrega timestamptz,
    usuario_asigna_id bigint references usuario(id),
    observaciones text,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    constraint asignacion_recurso_destino check (
        (incidente_id is not null and refugio_id is null)
        or
        (incidente_id is null and refugio_id is not null)
    )
);

-- tabla asignacion_personal
create table asignacion_personal (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null references usuario(id),
    incidente_id bigint references incidente(id),
    refugio_id bigint references refugio(id),
    rol_asignado varchar(30) not null default 'APOYO'
        check (rol_asignado in ('COORDINACION', 'RESCATE', 'APOYO', 'LOGISTICA', 'GESTION_REFUGIO')),
    estado varchar(30) not null default 'ASIGNADO'
        check (estado in ('ASIGNADO', 'EN_CAMINO', 'ACTIVO', 'FINALIZADO', 'CANCELADO')),
    fecha_asignacion timestamptz not null default now(),
    fecha_finalizacion timestamptz,
    observaciones text,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    constraint asignacion_personal_destino check (
        (incidente_id is not null and refugio_id is null)
        or
        (incidente_id is null and refugio_id is not null)
    )
);

-- tabla alerta
create table alerta (
    id bigint generated by default as identity primary key,
    incidente_id bigint references incidente(id),
    zona_id bigint references zona(id),
    refugio_id bigint references refugio(id),
    tipo varchar(30) not null
        check (tipo in ('EMERGENCIA', 'RECURSO', 'REFUGIO', 'SEGUIMIENTO', 'OTRO')),
    nivel varchar(20) not null
        check (nivel in ('INFO', 'ADVERTENCIA', 'CRITICA')),
    mensaje text not null,
    estado varchar(20) not null default 'ACTIVA'
        check (estado in ('ACTIVA', 'LEIDA', 'RESUELTA')),
    fecha timestamptz not null default now(),
    constraint alerta_destino check (
        incidente_id is not null
        or zona_id is not null
        or refugio_id is not null
    )
);

-- tabla historial_incidente
create table historial_incidente (
    id bigint generated by default as identity primary key,
    incidente_id bigint not null references incidente(id),
    estado_anterior varchar(30),
    estado_nuevo varchar(30) not null
        check (estado_nuevo in ('REPORTADO', 'EN_ATENCION', 'MITIGADO', 'CERRADO')),
    comentario text,
    usuario_id bigint references usuario(id),
    fecha timestamptz not null default now()
);


-- ============================================
-- Procedimientos Almacenados
-- ============================================

-- listar todos los usuarios activos
create or replace function sp_listar_usuarios()
returns table (
    id bigint,
    nombre varchar(120),
    email varchar(160),
    telefono varchar(30),
    rol varchar(30),
    activo boolean,
    habilidades text,
    disponible boolean,
    created_at timestamptz
) as $$
begin
    return query
    select u.id, u.nombre, u.email, u.telefono, u.rol, u.activo, 
           u.habilidades, u.disponible, u.created_at
    from usuario u
    where u.activo = true
    order by u.created_at desc;
end;
$$ language plpgsql;

-- agregar nuevo usuario
create or replace procedure sp_agregar_usuario(
    p_nombre varchar,
    p_email varchar,
    p_password_hash varchar,
    p_telefono varchar default null,
    p_rol varchar default 'VOLUNTARIO',
    p_habilidades text default null,
    p_disponible boolean default false
) as $$
begin
    insert into usuario (nombre, email, password_hash, telefono, rol, habilidades, disponible)
    values (p_nombre, p_email, p_password_hash, p_telefono, p_rol, p_habilidades, p_disponible);
end;
$$ language plpgsql;

-- buscar usuario por id (CORREGIDO: Columnas explícitas)
create or replace function sp_buscar_usuario(p_id bigint)
returns table (
    id bigint,
    nombre varchar(120),
    email varchar(160),
    telefono varchar(30),
    rol varchar(30),
    activo boolean,
    habilidades text,
    disponible boolean,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select u.id, u.nombre, u.email, u.telefono, u.rol, u.activo, 
           u.habilidades, u.disponible, u.created_at, u.updated_at
    from usuario u
    where u.id = p_id and u.activo = true;
end;
$$ language plpgsql;

-- actualizar usuario
create or replace procedure sp_actualizar_usuario(
    p_id bigint,
    p_nombre varchar,
    p_email varchar,
    p_telefono varchar,
    p_rol varchar,
    p_habilidades text,
    p_disponible boolean
) as $$
begin
    update usuario
    set nombre = p_nombre,
        email = p_email,
        telefono = p_telefono,
        rol = p_rol,
        habilidades = p_habilidades,
        disponible = p_disponible,
        updated_at = now()
    where id = p_id and activo = true;
end;
$$ language plpgsql;

-- eliminar usuario (soft delete)
create or replace procedure sp_eliminar_usuario(p_id bigint) as $$
begin
    update usuario
    set activo = false,
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;


-- ============================================
-- procedimientos para tabla zona
-- ============================================

-- listar todas las zonas activas
create or replace function sp_listar_zonas()
returns table (
    id bigint,
    nombre varchar,
    municipio varchar,
    departamento varchar,
    pais varchar,
    latitud numeric,
    longitud numeric,
    nivel_riesgo varchar,
    activo boolean,
    created_at timestamptz
) as $$
begin
    return query
    select z.id, z.nombre, z.municipio, z.departamento, z.pais, z.latitud, z.longitud,
           z.nivel_riesgo, z.activo, z.created_at
    from zona z
    where z.activo = true
    order by z.id asc;
end;
$$ language plpgsql;

-- agregar nueva zona
create or replace procedure sp_agregar_zona(
    p_nombre varchar,
    p_municipio varchar default null,
    p_departamento varchar default null,
    p_pais varchar default 'Guatemala',
    p_latitud numeric default null,
    p_longitud numeric default null,
    p_nivel_riesgo varchar default 'MEDIO'
) as $$
begin
    insert into zona (nombre, municipio, departamento, pais, latitud, longitud, nivel_riesgo)
    values (p_nombre, p_municipio, p_departamento, p_pais, p_latitud, p_longitud, p_nivel_riesgo);
end;
$$ language plpgsql;

-- buscar zona por id
create or replace function sp_buscar_zona(p_id bigint)
returns table (
    id bigint,
    nombre varchar,
    municipio varchar,
    departamento varchar,
    pais varchar,
    latitud numeric,
    longitud numeric,
    nivel_riesgo varchar,
    activo boolean,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select z.*
    from zona z
    where z.id = p_id and z.activo = true;
end;
$$ language plpgsql;

-- actualizar zona
create or replace procedure sp_actualizar_zona(
    p_id bigint,
    p_nombre varchar,
    p_municipio varchar,
    p_departamento varchar,
    p_pais varchar,
    p_latitud numeric,
    p_longitud numeric,
    p_nivel_riesgo varchar
) as $$
begin
    update zona
    set nombre = p_nombre,
        municipio = p_municipio,
        departamento = p_departamento,
        pais = p_pais,
        latitud = p_latitud,
        longitud = p_longitud,
        nivel_riesgo = p_nivel_riesgo,
        updated_at = now()
    where id = p_id and activo = true;
end;
$$ language plpgsql;

-- eliminar zona (soft delete)
create or replace procedure sp_eliminar_zona(p_id bigint) as $$
begin
    update zona
    set activo = false,
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;


-- ============================================
-- procedimientos para tabla incidente
-- ============================================

-- listar todos los incidentes
create or replace function sp_listar_incidentes()
returns table (
    id bigint,
    tipo varchar,
    titulo varchar,
    descripcion text,
    nivel_emergencia varchar,
    estado varchar,
    fecha_reporte timestamptz,
    fecha_cierre timestamptz,
    zona_id bigint,
    reportado_por bigint,
    latitud numeric,
    longitud numeric,
    cantidad_personas_afectadas integer,
    created_at timestamptz
) as $$
begin
    return query
    select i.id, i.tipo, i.titulo, i.descripcion, i.nivel_emergencia, i.estado,
           i.fecha_reporte, i.fecha_cierre, i.zona_id, i.reportado_por,
           i.latitud, i.longitud, i.cantidad_personas_afectadas, i.created_at
    from incidente i
    order by i.id asc;
end;
$$ language plpgsql;

-- agregar nuevo incidente
create or replace procedure sp_agregar_incidente(
    p_tipo varchar,
    p_titulo varchar,
    p_descripcion text,
    p_zona_id bigint,
    p_reportado_por bigint,
    p_nivel_emergencia varchar default 'MEDIA',
    p_latitud numeric default null,
    p_longitud numeric default null,
    p_cantidad_personas_afectadas integer default null
) as $$
begin
    insert into incidente (tipo, titulo, descripcion, nivel_emergencia, zona_id, 
                          reportado_por, latitud, longitud, cantidad_personas_afectadas)
    values (p_tipo, p_titulo, p_descripcion, p_nivel_emergencia, p_zona_id,
            p_reportado_por, p_latitud, p_longitud, p_cantidad_personas_afectadas);
end;
$$ language plpgsql;

-- buscar incidente por id
create or replace function sp_buscar_incidente(p_id bigint)
returns table (
    id bigint,
    tipo varchar,
    titulo varchar,
    descripcion text,
    nivel_emergencia varchar,
    estado varchar,
    fecha_reporte timestamptz,
    fecha_cierre timestamptz,
    zona_id bigint,
    reportado_por bigint,
    latitud numeric,
    longitud numeric,
    cantidad_personas_afectadas integer,
    observaciones text,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select i.*
    from incidente i
    where i.id = p_id;
end;
$$ language plpgsql;

-- actualizar incidente
create or replace procedure sp_actualizar_incidente(
    p_id bigint,
    p_estado varchar,
    p_observaciones text,
    p_fecha_cierre timestamptz default null
) as $$
begin
    update incidente
    set estado = p_estado,
        observaciones = p_observaciones,
        fecha_cierre = p_fecha_cierre,
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- eliminar incidente (soft delete - marcar como cerrado)
create or replace procedure sp_eliminar_incidente(p_id bigint) as $$
begin
    update incidente
    set estado = 'CERRADO',
        fecha_cierre = now(),
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;


-- ============================================
-- procedimientos para tabla refugio
-- ============================================

-- listar todos los refugios activos
create or replace function sp_listar_refugios()
returns table (
    id bigint,
    nombre varchar,
    direccion text,
    zona_id bigint,
    latitud numeric,
    longitud numeric,
    capacidad_total integer,
    ocupacion_actual integer,
    estado varchar,
    responsable_id bigint,
    telefono_contacto varchar,
    activo boolean,
    created_at timestamptz
) as $$
begin
    return query
    select r.id, r.nombre, r.direccion, r.zona_id, r.latitud, r.longitud,
           r.capacidad_total, r.ocupacion_actual, r.estado, r.responsable_id,
           r.telefono_contacto, r.activo, r.created_at
    from refugio r
    where r.activo = true
    order by r.id asc;
end;
$$ language plpgsql;

-- agregar nuevo refugio
create or replace procedure sp_agregar_refugio(
    p_nombre varchar,
    p_capacidad_total integer,
    p_direccion text default null,
    p_zona_id bigint default null,
    p_latitud numeric default null,
    p_longitud numeric default null,
    p_responsable_id bigint default null,
    p_telefono_contacto varchar default null
) as $$
begin
    insert into refugio (nombre, direccion, zona_id, latitud, longitud, 
                        capacidad_total, responsable_id, telefono_contacto)
    values (p_nombre, p_direccion, p_zona_id, p_latitud, p_longitud,
            p_capacidad_total, p_responsable_id, p_telefono_contacto);
end;
$$ language plpgsql;

-- buscar refugio por id
create or replace function sp_buscar_refugio(p_id bigint)
returns table (
    id bigint,
    nombre varchar,
    direccion text,
    zona_id bigint,
    latitud numeric,
    longitud numeric,
    capacidad_total integer,
    ocupacion_actual integer,
    estado varchar,
    responsable_id bigint,
    telefono_contacto varchar,
    observaciones text,
    activo boolean,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select r.*
    from refugio r
    where r.id = p_id and r.activo = true;
end;
$$ language plpgsql;

-- actualizar refugio
create or replace procedure sp_actualizar_refugio(
    p_id bigint,
    p_nombre varchar,
    p_direccion text,
    p_zona_id bigint,
    p_latitud numeric,
    p_longitud numeric,
    p_capacidad_total integer,
    p_ocupacion_actual integer,
    p_estado varchar,
    p_responsable_id bigint,
    p_telefono_contacto varchar,
    p_observaciones text
) as $$
begin
    update refugio
    set nombre = p_nombre,
        direccion = p_direccion,
        zona_id = p_zona_id,
        latitud = p_latitud,
        longitud = p_longitud,
        capacidad_total = p_capacidad_total,
        ocupacion_actual = p_ocupacion_actual,
        estado = p_estado,
        responsable_id = p_responsable_id,
        telefono_contacto = p_telefono_contacto,
        observaciones = p_observaciones,
        updated_at = now()
    where id = p_id and activo = true;
end;
$$ language plpgsql;

-- eliminar refugio (soft delete)
create or replace procedure sp_eliminar_refugio(p_id bigint) as $$
begin
    update refugio
    set activo = false,
        estado = 'INACTIVO',
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;


-- ============================================
-- procedimientos para tabla recurso
-- ============================================

-- listar todos los recursos activos
create or replace function sp_listar_recursos()
returns table (
    id bigint,
    nombre varchar,
    tipo varchar,
    unidad_medida varchar,
    cantidad_total integer,
    descripcion text,
    activo boolean,
    created_at timestamptz
) as $$
begin
    return query
    select r.id, r.nombre, r.tipo, r.unidad_medida, r.cantidad_total,
           r.descripcion, r.activo, r.created_at
    from recurso r
    where r.activo = true
    order by r.id asc;
end;
$$ language plpgsql;

-- agregar nuevo recurso
create or replace procedure sp_agregar_recurso(
    p_nombre varchar,
    p_tipo varchar,
    p_unidad_medida varchar default 'UNIDAD',
    p_cantidad_total integer default 0,
    p_descripcion text default null
) as $$
begin
    insert into recurso (nombre, tipo, unidad_medida, cantidad_total, descripcion)
    values (p_nombre, p_tipo, p_unidad_medida, p_cantidad_total, p_descripcion);
end;
$$ language plpgsql;

-- buscar recurso por id
create or replace function sp_buscar_recurso(p_id bigint)
returns table (
    id bigint,
    nombre varchar,
    tipo varchar,
    unidad_medida varchar,
    cantidad_total integer,
    descripcion text,
    activo boolean,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select r.*
    from recurso r
    where r.id = p_id and r.activo = true;
end;
$$ language plpgsql;

-- actualizar recurso
create or replace procedure sp_actualizar_recurso(
    p_id bigint,
    p_nombre varchar,
    p_tipo varchar,
    p_unidad_medida varchar,
    p_cantidad_total integer,
    p_descripcion text
) as $$
begin
    update recurso
    set nombre = p_nombre,
        tipo = p_tipo,
        unidad_medida = p_unidad_medida,
        cantidad_total = p_cantidad_total,
        descripcion = p_descripcion,
        updated_at = now()
    where id = p_id and activo = true;
end;
$$ language plpgsql;

-- eliminar recurso (soft delete)
create or replace procedure sp_eliminar_recurso(p_id bigint) as $$
begin
    update recurso
    set activo = false,
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;


-- ============================================
-- procedimientos para tabla asignacion_recurso
-- ============================================

-- listar todas las asignaciones de recursos
create or replace function sp_listar_asignaciones_recurso()
returns table (
    id bigint,
    recurso_id bigint,
    nombre_recurso varchar,
    incidente_id bigint,
    refugio_id bigint,
    cantidad integer,
    estado varchar,
    fecha_solicitud timestamptz,
    fecha_asignacion timestamptz,
    fecha_entrega timestamptz,
    usuario_asigna_id bigint,
    observaciones text,
    created_at timestamptz
) as $$
begin
    return query
    select ar.id, ar.recurso_id, r.nombre as nombre_recurso,
           ar.incidente_id, ar.refugio_id, ar.cantidad, ar.estado,
           ar.fecha_solicitud, ar.fecha_asignacion, ar.fecha_entrega,
           ar.usuario_asigna_id, ar.observaciones, ar.created_at
    from asignacion_recurso ar
    inner join recurso r on r.id = ar.recurso_id
    order by ar.id asc;
end;
$$ language plpgsql;

-- agregar nueva asignacion de recurso
create or replace procedure sp_agregar_asignacion_recurso(
    p_recurso_id bigint,
    p_cantidad integer,
    p_estado varchar default 'SOLICITADO',
    p_incidente_id bigint default null,
    p_refugio_id bigint default null,
    p_usuario_asigna_id bigint default null,
    p_observaciones text default null
) as $$
begin
    insert into asignacion_recurso (recurso_id, incidente_id, refugio_id, cantidad,
                                    estado, usuario_asigna_id, observaciones)
    values (p_recurso_id, p_incidente_id, p_refugio_id, p_cantidad,
            p_estado, p_usuario_asigna_id, p_observaciones);
end;
$$ language plpgsql;

-- buscar asignacion de recurso por id
create or replace function sp_buscar_asignacion_recurso(p_id bigint)
returns table (
    id bigint,
    recurso_id bigint,
    incidente_id bigint,
    refugio_id bigint,
    cantidad integer,
    estado varchar,
    fecha_solicitud timestamptz,
    fecha_asignacion timestamptz,
    fecha_entrega timestamptz,
    usuario_asigna_id bigint,
    observaciones text,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select ar.*
    from asignacion_recurso ar
    where ar.id = p_id;
end;
$$ language plpgsql;

-- actualizar asignacion de recurso
create or replace procedure sp_actualizar_asignacion_recurso(
    p_id bigint,
    p_cantidad integer,
    p_estado varchar,
    p_fecha_asignacion timestamptz default null,
    p_fecha_entrega timestamptz default null,
    p_observaciones text default null
) as $$
begin
    update asignacion_recurso
    set cantidad = p_cantidad,
        estado = p_estado,
        fecha_asignacion = coalesce(p_fecha_asignacion, fecha_asignacion),
        fecha_entrega = coalesce(p_fecha_entrega, fecha_entrega),
        observaciones = coalesce(p_observaciones, observaciones),
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- eliminar asignacion de recurso (soft delete - marcar como cancelado)
create or replace procedure sp_eliminar_asignacion_recurso(p_id bigint) as $$
begin
    update asignacion_recurso
    set estado = 'CANCELADO',
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;


-- ============================================
-- procedimientos para tabla asignacion_personal
-- ============================================

-- listar todas las asignaciones de personal
create or replace function sp_listar_asignaciones_personal()
returns table (
    id bigint,
    usuario_id bigint,
    nombre_usuario varchar,
    incidente_id bigint,
    refugio_id bigint,
    rol_asignado varchar,
    estado varchar,
    fecha_asignacion timestamptz,
    fecha_finalizacion timestamptz,
    observaciones text,
    created_at timestamptz
) as $$
begin
    return query
    select ap.id, ap.usuario_id, u.nombre as nombre_usuario,
           ap.incidente_id, ap.refugio_id, ap.rol_asignado, ap.estado,
           ap.fecha_asignacion, ap.fecha_finalizacion, ap.observaciones,
           ap.created_at
    from asignacion_personal ap
    inner join usuario u on u.id = ap.usuario_id
    order by ap.id asc;
end;
$$ language plpgsql;

-- agregar nueva asignacion de personal
create or replace procedure sp_agregar_asignacion_personal(
    p_usuario_id bigint,
    p_rol_asignado varchar default 'APOYO',
    p_estado varchar default 'ASIGNADO',
    p_incidente_id bigint default null,
    p_refugio_id bigint default null,
    p_observaciones text default null
) as $$
begin
    insert into asignacion_personal (usuario_id, incidente_id, refugio_id,
                                     rol_asignado, estado, observaciones)
    values (p_usuario_id, p_incidente_id, p_refugio_id,
            p_rol_asignado, p_estado, p_observaciones);
end;
$$ language plpgsql;

-- buscar asignacion de personal por id
create or replace function sp_buscar_asignacion_personal(p_id bigint)
returns table (
    id bigint,
    usuario_id bigint,
    incidente_id bigint,
    refugio_id bigint,
    rol_asignado varchar,
    estado varchar,
    fecha_asignacion timestamptz,
    fecha_finalizacion timestamptz,
    observaciones text,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select ap.*
    from asignacion_personal ap
    where ap.id = p_id;
end;
$$ language plpgsql;

-- actualizar asignacion de personal
create or replace procedure sp_actualizar_asignacion_personal(
    p_id bigint,
    p_rol_asignado varchar,
    p_estado varchar,
    p_fecha_finalizacion timestamptz default null,
    p_observaciones text default null
) as $$
begin
    update asignacion_personal
    set rol_asignado = p_rol_asignado,
        estado = p_estado,
        fecha_finalizacion = coalesce(p_fecha_finalizacion, fecha_finalizacion),
        observaciones = coalesce(p_observaciones, observaciones),
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- eliminar asignacion de personal (soft delete - marcar como cancelado)
create or replace procedure sp_eliminar_asignacion_personal(p_id bigint) as $$
begin
    update asignacion_personal
    set estado = 'CANCELADO',
        fecha_finalizacion = now(),
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;


-- ============================================
-- procedimientos para tabla alerta
-- ============================================

-- listar todas las alertas
create or replace function sp_listar_alertas()
returns table (
    id bigint,
    incidente_id bigint,
    zona_id bigint,
    refugio_id bigint,
    tipo varchar,
    nivel varchar,
    mensaje text,
    estado varchar,
    fecha timestamptz
) as $$
begin
    return query
    select a.id, a.incidente_id, a.zona_id, a.refugio_id,
           a.tipo, a.nivel, a.mensaje, a.estado, a.fecha
    from alerta a
    order by a.id asc;
end;
$$ language plpgsql;

-- agregar nueva alerta
create or replace procedure sp_agregar_alerta(
    p_tipo varchar,
    p_nivel varchar,
    p_mensaje text,
    p_incidente_id bigint default null,
    p_zona_id bigint default null,
    p_refugio_id bigint default null
) as $$
begin
    insert into alerta (incidente_id, zona_id, refugio_id, tipo, nivel, mensaje)
    values (p_incidente_id, p_zona_id, p_refugio_id, p_tipo, p_nivel, p_mensaje);
end;
$$ language plpgsql;

-- buscar alerta por id
create or replace function sp_buscar_alerta(p_id bigint)
returns table (
    id bigint,
    incidente_id bigint,
    zona_id bigint,
    refugio_id bigint,
    tipo varchar,
    nivel varchar,
    mensaje text,
    estado varchar,
    fecha timestamptz
) as $$
begin
    return query
    select a.*
    from alerta a
    where a.id = p_id;
end;
$$ language plpgsql;

-- actualizar alerta
create or replace procedure sp_actualizar_alerta(
    p_id bigint,
    p_estado varchar
) as $$
begin
    update alerta
    set estado = p_estado
    where id = p_id;
end;
$$ language plpgsql;

-- eliminar alerta (soft delete - marcar como resuelta)
create or replace procedure sp_eliminar_alerta(p_id bigint) as $$
begin
    update alerta
    set estado = 'RESUELTA'
    where id = p_id;
end;
$$ language plpgsql;


-- ============================================
-- procedimientos para tabla historial_incidente
-- ============================================

-- listar todo el historial
create or replace function sp_listar_historial_incidentes()
returns table (
    id bigint,
    incidente_id bigint,
    estado_anterior varchar,
    estado_nuevo varchar,
    comentario text,
    usuario_id bigint,
    nombre_usuario varchar,
    fecha timestamptz
) as $$
begin
    return query
    select h.id, h.incidente_id, h.estado_anterior, h.estado_nuevo,
           h.comentario, h.usuario_id, u.nombre as nombre_usuario, h.fecha
    from historial_incidente h
    left join usuario u on u.id = h.usuario_id
    order by h.id asc;
end;
$$ language plpgsql;

-- agregar entrada al historial
create or replace procedure sp_agregar_historial_incidente(
    p_incidente_id bigint,
    p_estado_nuevo varchar,
    p_estado_anterior varchar default null,
    p_comentario text default null,
    p_usuario_id bigint default null
) as $$
begin
    insert into historial_incidente (incidente_id, estado_anterior, estado_nuevo,
                                     comentario, usuario_id)
    values (p_incidente_id, p_estado_anterior, p_estado_nuevo,
            p_comentario, p_usuario_id);
end;
$$ language plpgsql;

-- buscar entrada de historial por id
create or replace function sp_buscar_historial_por_id(p_id bigint)
returns table (
    id bigint,
    incidente_id bigint,
    estado_anterior varchar,
    estado_nuevo varchar,
    comentario text,
    usuario_id bigint,
    fecha timestamptz
) as $$
begin
    return query
    select h.*
    from historial_incidente h
    where h.id = p_id;
end;
$$ language plpgsql;

-- actualizar comentario de una entrada del historial
create or replace procedure sp_actualizar_historial_incidente(
    p_id bigint,
    p_comentario text
) as $$
begin
    update historial_incidente
    set comentario = p_comentario
    where id = p_id;
end;
$$ language plpgsql;

-- eliminar entrada del historial
create or replace procedure sp_eliminar_historial_incidente(p_id bigint) as $$
begin
    delete from historial_incidente
    where id = p_id;
end;
$$ language plpgsql;

-- ============================================
-- Inserción de registros por Entidad
-- ============================================
INSERT INTO usuario (nombre, email, password_hash, telefono, rol, activo, habilidades, disponible) VALUES
('Admin Principal', 'admin@sigid.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '5555-1001', 'ADMIN', true, 'Gestión completa del sistema', true),
('Carlos Coordinador', 'coordinador@sigid.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '5555-1002', 'COORDINADOR', true, 'Coordinación de operaciones', true),
('Juan Rescatista', 'rescatista@sigid.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '5555-1003', 'RESCATISTA', true, 'Rescate acuático y terrestre', true),
('María Voluntaria', 'voluntario@sigid.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '5555-1004', 'VOLUNTARIO', true, 'Apoyo logístico', true),
('Pedro Gestor', 'gestor@sigid.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '5555-1005', 'GESTOR_REFUGIO', true, 'Administración de refugios', true);

-- Zonas
call sp_agregar_zona('zona 1 guatemala', 'guatemala', 'guatemala', 'guatemala', 14.6349, -90.5069, 'MEDIO');
call sp_agregar_zona('quetzaltenango centro', 'quetzaltenango', 'quetzaltenango', 'guatemala', 14.8348, -91.5181, 'ALTO');
call sp_agregar_zona('escuintla costa', 'escuintla', 'escuintla', 'guatemala', 14.3050, -90.7850, 'ALTO');
call sp_agregar_zona('petén norte', 'flores', 'petén', 'guatemala', 16.9281, -89.8990, 'BAJO');
call sp_agregar_zona('huehuetenango sierra', 'huehuetenango', 'huehuetenango', 'guatemala', 15.3197, -91.4714, 'CRITICO');

-- Incidentes
call sp_agregar_incidente('INUNDACION', 'inundación zona 1 guatemala', 'desbordamiento del río por lluvias intensas', 1, 2, 'ALTA', 14.6400, -90.5100, 150);
call sp_agregar_incidente('TERREMOTO', 'sismo magnitud 5.8 quetzaltenango', 'movimiento telúrico registrado en la región', 2, 2, 'MEDIA', 14.8400, -91.5200, 75);
call sp_agregar_incidente('INCENDIO', 'incendio forestal escuintla', 'fuego en vegetación por altas temperaturas', 3, 3, 'CRITICA', 14.3100, -90.7900, 200);
call sp_agregar_incidente('DESLIZAMIENTO', 'deslizamiento huehuetenango', 'desprendimiento de tierra por lluvias', 5, 2, 'ALTA', 15.3250, -91.4800, 50);
call sp_agregar_incidente('ACTIVIDAD_VOLCANICA', 'actividad volcán de fuego', 'aumento en actividad sísmica y emisión de ceniza', 2, 2, 'MEDIA', 14.4730, -90.8800, 300);

-- Refugios
call sp_agregar_refugio('refugio centro comunitario zona 1', 100, 'avenida principal 123, zona 1', 1, 14.6350, -90.5070, 4, '5555-2001');
call sp_agregar_refugio('albergue municipal quetzaltenango', 150, 'calle 5ta avenida 456', 2, 14.8350, -91.5180, 4, '5555-2002');
call sp_agregar_refugio('refugio escuintla costa', 80, 'barrio el progreso', 3, 14.3055, -90.7855, 4, '5555-2003');
call sp_agregar_refugio('albergue petén norte', 120, 'zona 3 flores', 4, 16.9285, -89.8995, 4, '5555-2004');
call sp_agregar_refugio('refugio huehuetenango sierra', 90, 'aldea san juan', 5, 15.3200, -91.4720, 4, '5555-2005');

-- Recursos
call sp_agregar_recurso('agua embotellada', 'AGUA', 'CAJA', 500, 'cajas de 24 botellas de 500ml');
call sp_agregar_recurso('arroz y frijoles', 'ALIMENTO', 'KILOGRAMO', 1000, 'sacos de arroz y frijoles');
call sp_agregar_recurso('kit primeros auxilios', 'MEDICAMENTO', 'UNIDAD', 200, 'kits completos de primeros auxilios');
call sp_agregar_recurso('mantas térmicas', 'EQUIPO', 'UNIDAD', 300, 'mantas para damnificados');
call sp_agregar_recurso('camioneta rescate', 'VEHICULO', 'UNIDAD', 5, 'vehículos 4x4 para rescate');

-- Asignacion_recurso
call sp_agregar_asignacion_recurso(1, 50, 'ENTREGADO', 1, null, 2, 'agua para damnificados por inundación');
call sp_agregar_asignacion_recurso(2, 200, 'ENTREGADO', null, 1, 2, 'alimentos para refugio zona 1');
call sp_agregar_asignacion_recurso(3, 30, 'ENVIADO', 3, null, 2, 'kits médicos para incendio forestal');
call sp_agregar_asignacion_recurso(4, 100, 'ASIGNADO', null, 2, 4, 'mantas para albergue quetzaltenango');
call sp_agregar_asignacion_recurso(1, 80, 'SOLICITADO', 5, null, 2, 'agua para actividad volcánica');

-- Asignacion_personal
call sp_agregar_asignacion_personal(3, 'RESCATE', 'ACTIVO', 1, null, 'rescate acuático en zona inundada');
call sp_agregar_asignacion_personal(2, 'COORDINACION', 'ACTIVO', null, 1, 'coordinación de albergue');
call sp_agregar_asignacion_personal(5, 'APOYO', 'EN_CAMINO', 3, null, 'apoyo en incendio forestal');
call sp_agregar_asignacion_personal(4, 'GESTION_REFUGIO', 'ACTIVO', null, 3, 'gestión de albergue escuintla');
call sp_agregar_asignacion_personal(3, 'RESCATE', 'FINALIZADO', 4, null, 'rescate en deslizamiento completado');

-- Alertas
call sp_agregar_alerta('EMERGENCIA', 'CRITICA', 'inundación severa en zona 1, evacuar inmediatamente', 1, null, null);
call sp_agregar_alerta('RECURSO', 'ADVERTENCIA', 'stock de agua bajo en refugio 2', null, null, 2);
call sp_agregar_alerta('REFUGIO', 'ADVERTENCIA', 'refugio 3 alcanzó 90% de capacidad', null, null, 3);
call sp_agregar_alerta('SEGUIMIENTO', 'INFO', 'incendio forestal bajo control, 60% mitigado', 3, null, null);
call sp_agregar_alerta('EMERGENCIA', 'CRITICA', 'actividad volcánica incrementada, mantenerse alerta', 5, 2, null);

-- Historial_incidente
call sp_agregar_historial_incidente(1, 'EN_ATENCION', 'REPORTADO', 'equipo de rescate desplegado en zona', 2);
call sp_agregar_historial_incidente(2, 'MITIGADO', 'EN_ATENCION', 'evaluación de daños completada', 2);
call sp_agregar_historial_incidente(3, 'EN_ATENCION', 'REPORTADO', 'bomberos en el lugar combatiendo fuego', 3);
call sp_agregar_historial_incidente(4, 'CERRADO', 'MITIGADO', 'zona estabilizada, residentes retornados', 2);
call sp_agregar_historial_incidente(5, 'EN_ATENCION', 'REPORTADO', 'monitoreo volcánico activo, evacuación preventiva', 2);

