-- tabla asignacion_personal
create table asignacion_personal (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null references usuario(id),
    incidente_id bigint references incidente(id),
    refugio_id bigint references refugio(id),
    rol_asignado varchar(30) not null default 'APOYO'
        check (rol_asignado in ('COORDINACION', 'RESCATE', 'APOYO', 'LOGISTICA', 'GESTION_REFUGIO')),
    estado varchar(30) not null default 'ASIGNADO'
        check (estado in ('ASIGNADO', 'EN_CAMINO', 'ACTIVO', 'FINALIZADO', 'CANCELADO')),
    fecha_asignacion timestamptz not null default now(),
    fecha_finalizacion timestamptz,
    observaciones text,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    constraint asignacion_personal_destino check (
        (incidente_id is not null and refugio_id is null)
        or
        (incidente_id is null and refugio_id is not null)
    )
);

-- tabla alerta
create table alerta (
    id bigint generated by default as identity primary key,
    incidente_id bigint references incidente(id),
    zona_id bigint references zona(id),
    refugio_id bigint references refugio(id),
    tipo varchar(30) not null
        check (tipo in ('EMERGENCIA', 'RECURSO', 'REFUGIO', 'SEGUIMIENTO', 'OTRO')),
    nivel varchar(20) not null
        check (nivel in ('INFO', 'ADVERTENCIA', 'CRITICA')),
    mensaje text not null,
    estado varchar(20) not null default 'ACTIVA'
        check (estado in ('ACTIVA', 'LEIDA', 'RESUELTA')),
    fecha timestamptz not null default now(),
    constraint alerta_destino check (
        incidente_id is not null
        or zona_id is not null
        or refugio_id is not null
    )
);

-- listar todas las asignaciones de personal
create or replace function sp_listar_asignaciones_personal()
returns table (
    id bigint,
    usuario_id bigint,
    nombre_usuario varchar,
    incidente_id bigint,
    refugio_id bigint,
    rol_asignado varchar,
    estado varchar,
    fecha_asignacion timestamptz,
    fecha_finalizacion timestamptz,
    observaciones text,
    created_at timestamptz
) as $$
begin
    return query
    select ap.id, ap.usuario_id, u.nombre as nombre_usuario,
           ap.incidente_id, ap.refugio_id, ap.rol_asignado, ap.estado,
           ap.fecha_asignacion, ap.fecha_finalizacion, ap.observaciones,
           ap.created_at
    from asignacion_personal ap
    inner join usuario u on u.id = ap.usuario_id
    order by ap.fecha_asignacion desc;
end;
$$ language plpgsql;

-- agregar nueva asignacion de personal
create or replace procedure sp_agregar_asignacion_personal(
    p_usuario_id bigint,
    p_rol_asignado varchar default 'APOYO',
    p_estado varchar default 'ASIGNADO',
    p_incidente_id bigint default null,
    p_refugio_id bigint default null,
    p_observaciones text default null
) as $$
begin
    insert into asignacion_personal (usuario_id, incidente_id, refugio_id,
                                     rol_asignado, estado, observaciones)
    values (p_usuario_id, p_incidente_id, p_refugio_id,
            p_rol_asignado, p_estado, p_observaciones);
end;
$$ language plpgsql;

-- buscar asignacion de personal por id
create or replace function sp_buscar_asignacion_personal(p_id bigint)
returns table (
    id bigint,
    usuario_id bigint,
    incidente_id bigint,
    refugio_id bigint,
    rol_asignado varchar,
    estado varchar,
    fecha_asignacion timestamptz,
    fecha_finalizacion timestamptz,
    observaciones text,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select ap.*
    from asignacion_personal ap
    where ap.id = p_id;
end;
$$ language plpgsql;

-- actualizar asignacion de personal
create or replace procedure sp_actualizar_asignacion_personal(
    p_id bigint,
    p_rol_asignado varchar,
    p_estado varchar,
    p_fecha_finalizacion timestamptz default null,
    p_observaciones text default null
) as $$
begin
    update asignacion_personal
    set rol_asignado = p_rol_asignado,
        estado = p_estado,
        fecha_finalizacion = coalesce(p_fecha_finalizacion, fecha_finalizacion),
        observaciones = coalesce(p_observaciones, observaciones),
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- eliminar asignacion de personal (marcar como cancelado)
create or replace procedure sp_eliminar_asignacion_personal(p_id bigint) as $$
begin
    update asignacion_personal
    set estado = 'CANCELADO',
        fecha_finalizacion = now(),
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- listar todas las alertas
create or replace function sp_listar_alertas()
returns table (
    id bigint,
    incidente_id bigint,
    zona_id bigint,
    refugio_id bigint,
    tipo varchar,
    nivel varchar,
    mensaje text,
    estado varchar,
    fecha timestamptz
) as $$
begin
    return query
    select a.id, a.incidente_id, a.zona_id, a.refugio_id,
           a.tipo, a.nivel, a.mensaje, a.estado, a.fecha
    from alerta a
    order by a.fecha desc;
end;
$$ language plpgsql;

-- agregar nueva alerta
create or replace procedure sp_agregar_alerta(
    p_tipo varchar,
    p_nivel varchar,
    p_mensaje text,
    p_incidente_id bigint default null,
    p_zona_id bigint default null,
    p_refugio_id bigint default null
) as $$
begin
    insert into alerta (incidente_id, zona_id, refugio_id, tipo, nivel, mensaje)
    values (p_incidente_id, p_zona_id, p_refugio_id, p_tipo, p_nivel, p_mensaje);
end;
$$ language plpgsql;

-- buscar alerta por id
create or replace function sp_buscar_alerta(p_id bigint)
returns table (
    id bigint,
    incidente_id bigint,
    zona_id bigint,
    refugio_id bigint,
    tipo varchar,
    nivel varchar,
    mensaje text,
    estado varchar,
    fecha timestamptz
) as $$
begin
    return query
    select a.*
    from alerta a
    where a.id = p_id;
end;
$$ language plpgsql;

-- actualizar alerta
create or replace procedure sp_actualizar_alerta(
    p_id bigint,
    p_estado varchar
) as $$
begin
    update alerta
    set estado = p_estado
    where id = p_id;
end;
$$ language plpgsql;

-- eliminar alerta (marcar como resuelta)
create or replace procedure sp_eliminar_alerta(p_id bigint) as $$
begin
    update alerta
    set estado = 'RESUELTA'
    where id = p_id;
end;
$$ language plpgsql;