-- Eliminar tablas existentes 
drop table if exists asignacion_recurso cascade;
drop table if exists recurso cascade;
drop table if exists refugio cascade;

-- ELiminar funciones existentes
drop function if exists sp_listar_refugios() cascade;
drop function if exists sp_buscar_refugio(bigint) cascade;
drop function if exists sp_listar_recursos() cascade;
drop function if exists sp_buscar_recurso(bigint) cascade;
drop function if exists sp_listar_asignaciones_recurso() cascade;
drop function if exists sp_buscar_asignacion_recurso(bigint) cascade;

-- tabla refugio
create table refugio (
    id bigint generated by default as identity primary key,
    nombre varchar(160) not null,
    direccion text,
    zona_id bigint references zona(id),
    latitud numeric(9,6),
    longitud numeric(9,6),
    capacidad_total integer not null check (capacidad_total >= 0),
    ocupacion_actual integer not null default 0 check (ocupacion_actual >= 0),
    estado varchar(20) not null default 'DISPONIBLE'
        check (estado in ('DISPONIBLE', 'PARCIAL', 'LLENO', 'INACTIVO')),
    responsable_id bigint references usuario(id),
    telefono_contacto varchar(30),
    observaciones text,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    constraint refugio_ocupacion_max check (ocupacion_actual <= capacidad_total)
);

-- tabla recurso
create table recurso (
    id bigint generated by default as identity primary key,
    nombre varchar(120) not null,
    tipo varchar(30) not null
        check (tipo in ('AGUA', 'ALIMENTO', 'MEDICAMENTO', 'EQUIPO', 'VEHICULO', 'OTRO')),
    unidad_medida varchar(30) not null default 'UNIDAD'
        check (unidad_medida in ('UNIDAD', 'CAJA', 'KILOGRAMO', 'LITRO', 'PERSONA', 'OTRO')),
    cantidad_total integer not null default 0 check (cantidad_total >= 0),
    descripcion text,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

-- tabla asignacion_recurso
create table asignacion_recurso (
    id bigint generated by default as identity primary key,
    recurso_id bigint not null references recurso(id),
    incidente_id bigint references incidente(id),
    refugio_id bigint references refugio(id),
    cantidad integer not null check (cantidad > 0),
    estado varchar(30) not null default 'SOLICITADO'
        check (estado in ('SOLICITADO', 'ASIGNADO', 'ENVIADO', 'ENTREGADO', 'CANCELADO')),
    fecha_solicitud timestamptz not null default now(),
    fecha_asignacion timestamptz,
    fecha_entrega timestamptz,
    usuario_asigna_id bigint references usuario(id),
    observaciones text,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    constraint asignacion_recurso_destino check (
        (incidente_id is not null and refugio_id is null)
        or
        (incidente_id is null and refugio_id is not null)
    )
);

-- listar todos los refugios activos
create or replace function sp_listar_refugios()
returns table (
    id bigint,
    nombre varchar,
    direccion text,
    zona_id bigint,
    latitud numeric,
    longitud numeric,
    capacidad_total integer,
    ocupacion_actual integer,
    estado varchar,
    responsable_id bigint,
    telefono_contacto varchar,
    activo boolean,
    created_at timestamptz
) as $$
begin
    return query
    select r.id, r.nombre, r.direccion, r.zona_id, r.latitud, r.longitud,
           r.capacidad_total, r.ocupacion_actual, r.estado, r.responsable_id,
           r.telefono_contacto, r.activo, r.created_at
    from refugio r
    where r.activo = true
    order by r.nombre;
end;
$$ language plpgsql;

-- agregar nuevo refugio
create or replace procedure sp_agregar_refugio(
    p_nombre varchar,
    p_capacidad_total integer,
    p_direccion text default null,
    p_zona_id bigint default null,
    p_latitud numeric default null,
    p_longitud numeric default null,
    p_responsable_id bigint default null,
    p_telefono_contacto varchar default null
) as $$
begin
    insert into refugio (nombre, direccion, zona_id, latitud, longitud, 
                        capacidad_total, responsable_id, telefono_contacto)
    values (p_nombre, p_direccion, p_zona_id, p_latitud, p_longitud,
            p_capacidad_total, p_responsable_id, p_telefono_contacto);
end;
$$ language plpgsql;

-- buscar refugio por id
create or replace function sp_buscar_refugio(p_id bigint)
returns table (
    id bigint,
    nombre varchar,
    direccion text,
    zona_id bigint,
    latitud numeric,
    longitud numeric,
    capacidad_total integer,
    ocupacion_actual integer,
    estado varchar,
    responsable_id bigint,
    telefono_contacto varchar,
    observaciones text,
    activo boolean,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select r.*
    from refugio r
    where r.id = p_id and r.activo = true;
end;
$$ language plpgsql;

-- actualizar refugio
create or replace procedure sp_actualizar_refugio(
    p_id bigint,
    p_nombre varchar,
    p_direccion text,
    p_zona_id bigint,
    p_latitud numeric,
    p_longitud numeric,
    p_capacidad_total integer,
    p_ocupacion_actual integer,
    p_estado varchar,
    p_responsable_id bigint,
    p_telefono_contacto varchar,
    p_observaciones text
) as $$
begin
    update refugio
    set nombre = p_nombre,
        direccion = p_direccion,
        zona_id = p_zona_id,
        latitud = p_latitud,
        longitud = p_longitud,
        capacidad_total = p_capacidad_total,
        ocupacion_actual = p_ocupacion_actual,
        estado = p_estado,
        responsable_id = p_responsable_id,
        telefono_contacto = p_telefono_contacto,
        observaciones = p_observaciones,
        updated_at = now()
    where id = p_id and activo = true;
end;
$$ language plpgsql;

-- eliminar refugio (soft delete)
create or replace procedure sp_eliminar_refugio(p_id bigint) as $$
begin
    update refugio
    set activo = false,
        estado = 'INACTIVO',
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- listar todos los recursos activos
create or replace function sp_listar_recursos()
returns table (
    id bigint,
    nombre varchar,
    tipo varchar,
    unidad_medida varchar,
    cantidad_total integer,
    descripcion text,
    activo boolean,
    created_at timestamptz
) as $$
begin
    return query
    select r.id, r.nombre, r.tipo, r.unidad_medida, r.cantidad_total,
           r.descripcion, r.activo, r.created_at
    from recurso r
    where r.activo = true
    order by r.nombre;
end;
$$ language plpgsql;

-- agregar nuevo recurso
create or replace procedure sp_agregar_recurso(
    p_nombre varchar,
    p_tipo varchar,
    p_unidad_medida varchar default 'UNIDAD',
    p_cantidad_total integer default 0,
    p_descripcion text default null
) as $$
begin
    insert into recurso (nombre, tipo, unidad_medida, cantidad_total, descripcion)
    values (p_nombre, p_tipo, p_unidad_medida, p_cantidad_total, p_descripcion);
end;
$$ language plpgsql;

-- buscar recurso por id
create or replace function sp_buscar_recurso(p_id bigint)
returns table (
    id bigint,
    nombre varchar,
    tipo varchar,
    unidad_medida varchar,
    cantidad_total integer,
    descripcion text,
    activo boolean,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select r.*
    from recurso r
    where r.id = p_id and r.activo = true;
end;
$$ language plpgsql;

-- actualizar recurso
create or replace procedure sp_actualizar_recurso(
    p_id bigint,
    p_nombre varchar,
    p_tipo varchar,
    p_unidad_medida varchar,
    p_cantidad_total integer,
    p_descripcion text
) as $$
begin
    update recurso
    set nombre = p_nombre,
        tipo = p_tipo,
        unidad_medida = p_unidad_medida,
        cantidad_total = p_cantidad_total,
        descripcion = p_descripcion,
        updated_at = now()
    where id = p_id and activo = true;
end;
$$ language plpgsql;

-- eliminar recurso (soft delete)
create or replace procedure sp_eliminar_recurso(p_id bigint) as $$
begin
    update recurso
    set activo = false,
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- listar todas las asignaciones de recursos
create or replace function sp_listar_asignaciones_recurso()
returns table (
    id bigint,
    recurso_id bigint,
    nombre_recurso varchar,
    incidente_id bigint,
    refugio_id bigint,
    cantidad integer,
    estado varchar,
    fecha_solicitud timestamptz,
    fecha_asignacion timestamptz,
    fecha_entrega timestamptz,
    usuario_asigna_id bigint,
    observaciones text,
    created_at timestamptz
) as $$
begin
    return query
    select ar.id, ar.recurso_id, r.nombre as nombre_recurso,
           ar.incidente_id, ar.refugio_id, ar.cantidad, ar.estado,
           ar.fecha_solicitud, ar.fecha_asignacion, ar.fecha_entrega,
           ar.usuario_asigna_id, ar.observaciones, ar.created_at
    from asignacion_recurso ar
    inner join recurso r on r.id = ar.recurso_id
    order by ar.fecha_solicitud desc;
end;
$$ language plpgsql;

-- agregar nueva asignacion de recurso
create or replace procedure sp_agregar_asignacion_recurso(
    p_recurso_id bigint,
    p_cantidad integer,
    p_estado varchar default 'SOLICITADO',
    p_incidente_id bigint default null,
    p_refugio_id bigint default null,
    p_usuario_asigna_id bigint default null,
    p_observaciones text default null
) as $$
begin
    insert into asignacion_recurso (recurso_id, incidente_id, refugio_id, cantidad,
                                    estado, usuario_asigna_id, observaciones)
    values (p_recurso_id, p_incidente_id, p_refugio_id, p_cantidad,
            p_estado, p_usuario_asigna_id, p_observaciones);
end;
$$ language plpgsql;

-- buscar asignacion de recurso por id
create or replace function sp_buscar_asignacion_recurso(p_id bigint)
returns table (
    id bigint,
    recurso_id bigint,
    incidente_id bigint,
    refugio_id bigint,
    cantidad integer,
    estado varchar,
    fecha_solicitud timestamptz,
    fecha_asignacion timestamptz,
    fecha_entrega timestamptz,
    usuario_asigna_id bigint,
    observaciones text,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select ar.*
    from asignacion_recurso ar
    where ar.id = p_id;
end;
$$ language plpgsql;

-- actualizar asignacion de recurso
create or replace procedure sp_actualizar_asignacion_recurso(
    p_id bigint,
    p_cantidad integer,
    p_estado varchar,
    p_fecha_asignacion timestamptz default null,
    p_fecha_entrega timestamptz default null,
    p_observaciones text default null
) as $$
begin
    update asignacion_recurso
    set cantidad = p_cantidad,
        estado = p_estado,
        fecha_asignacion = coalesce(p_fecha_asignacion, fecha_asignacion),
        fecha_entrega = coalesce(p_fecha_entrega, fecha_entrega),
        observaciones = coalesce(p_observaciones, observaciones),
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- eliminar asignacion de recurso (soft delete - marcar como cancelado)
create or replace procedure sp_eliminar_asignacion_recurso(p_id bigint) as $$
begin
    update asignacion_recurso
    set estado = 'CANCELADO',
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- Refugios
call sp_agregar_refugio('refugio centro comunitario zona 1', 100, 'avenida principal 123, zona 1', 1, 14.6350, -90.5070, 4, '5555-2001');
call sp_agregar_refugio('albergue municipal quetzaltenango', 150, 'calle 5ta avenida 456', 2, 14.8350, -91.5180, 4, '5555-2002');
call sp_agregar_refugio('refugio escuintla costa', 80, 'barrio el progreso', 3, 14.3055, -90.7855, 4, '5555-2003');
call sp_agregar_refugio('albergue petén norte', 120, 'zona 3 flores', 4, 16.9285, -89.8995, 4, '5555-2004');
call sp_agregar_refugio('refugio huehuetenango sierra', 90, 'aldea san juan', 5, 15.3200, -91.4720, 4, '5555-2005');

-- Recursos
call sp_agregar_recurso('agua embotellada', 'AGUA', 'CAJA', 500, 'cajas de 24 botellas de 500ml');
call sp_agregar_recurso('arroz y frijoles', 'ALIMENTO', 'KILOGRAMO', 1000, 'sacos de arroz y frijoles');
call sp_agregar_recurso('kit primeros auxilios', 'MEDICAMENTO', 'UNIDAD', 200, 'kits completos de primeros auxilios');
call sp_agregar_recurso('mantas térmicas', 'EQUIPO', 'UNIDAD', 300, 'mantas para damnificados');
call sp_agregar_recurso('camioneta rescate', 'VEHICULO', 'UNIDAD', 5, 'vehículos 4x4 para rescate');

-- Asignacion_recurso
call sp_agregar_asignacion_recurso(1, 50, 'ENTREGADO', 1, null, 2, 'agua para damnificados por inundación');
call sp_agregar_asignacion_recurso(2, 200, 'ENTREGADO', null, 1, 2, 'alimentos para refugio zona 1');
call sp_agregar_asignacion_recurso(3, 30, 'ENVIADO', 3, null, 2, 'kits médicos para incendio forestal');
call sp_agregar_asignacion_recurso(4, 100, 'ASIGNADO', null, 2, 4, 'mantas para albergue quetzaltenango');
call sp_agregar_asignacion_recurso(1, 80, 'SOLICITADO', 5, null, 2, 'agua para actividad volcánica');