-- tabla incidente
create table incidente (
    id bigint generated by default as identity primary key,
    tipo varchar(40) not null
        check (tipo in ('INUNDACION', 'TERREMOTO', 'INCENDIO', 'DESLIZAMIENTO', 'ACTIVIDAD_VOLCANICA', 'OTRO')),
    titulo varchar(160) not null,
    descripcion text,
    nivel_emergencia varchar(20) not null default 'MEDIA'
        check (nivel_emergencia in ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    estado varchar(30) not null default 'REPORTADO'
        check (estado in ('REPORTADO', 'EN_ATENCION', 'MITIGADO', 'CERRADO')),
    fecha_reporte timestamptz not null default now(),
    fecha_cierre timestamptz,
    zona_id bigint not null references zona(id),
    reportado_por bigint not null references usuario(id),
    latitud numeric(9,6),
    longitud numeric(9,6),
    cantidad_personas_afectadas integer check (cantidad_personas_afectadas >= 0),
    observaciones text,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

-- tabla historial_incidente
create table historial_incidente (
    id bigint generated by default as identity primary key,
    incidente_id bigint not null references incidente(id),
    estado_anterior varchar(30),
    estado_nuevo varchar(30) not null
        check (estado_nuevo in ('REPORTADO', 'EN_ATENCION', 'MITIGADO', 'CERRADO')),
    comentario text,
    usuario_id bigint references usuario(id),
    fecha timestamptz not null default now()
);

-- listar todos los incidentes
create or replace function sp_listar_incidentes()
returns table (
    id bigint,
    tipo varchar,
    titulo varchar,
    descripcion text,
    nivel_emergencia varchar,
    estado varchar,
    fecha_reporte timestamptz,
    fecha_cierre timestamptz,
    zona_id bigint,
    reportado_por bigint,
    latitud numeric,
    longitud numeric,
    cantidad_personas_afectadas integer,
    created_at timestamptz
) as $$
begin
    return query
    select i.id, i.tipo, i.titulo, i.descripcion, i.nivel_emergencia, i.estado,
           i.fecha_reporte, i.fecha_cierre, i.zona_id, i.reportado_por,
           i.latitud, i.longitud, i.cantidad_personas_afectadas, i.created_at
    from incidente i
    order by i.id asc;
end;
$$ language plpgsql;

-- agregar nuevo incidente
create or replace procedure sp_agregar_incidente(
    p_tipo varchar,
    p_titulo varchar,
    p_descripcion text,
    p_zona_id bigint,
    p_reportado_por bigint,
    p_nivel_emergencia varchar default 'MEDIA',
    p_latitud numeric default null,
    p_longitud numeric default null,
    p_cantidad_personas_afectadas integer default null
) as $$
begin
    insert into incidente (tipo, titulo, descripcion, nivel_emergencia, zona_id, 
                          reportado_por, latitud, longitud, cantidad_personas_afectadas)
    values (p_tipo, p_titulo, p_descripcion, p_nivel_emergencia, p_zona_id,
            p_reportado_por, p_latitud, p_longitud, p_cantidad_personas_afectadas);
end;
$$ language plpgsql;

-- buscar incidente por id
create or replace function sp_buscar_incidente(p_id bigint)
returns table (
    id bigint,
    tipo varchar,
    titulo varchar,
    descripcion text,
    nivel_emergencia varchar,
    estado varchar,
    fecha_reporte timestamptz,
    fecha_cierre timestamptz,
    zona_id bigint,
    reportado_por bigint,
    latitud numeric,
    longitud numeric,
    cantidad_personas_afectadas integer,
    observaciones text,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select i.*
    from incidente i
    where i.id = p_id;
end;
$$ language plpgsql;

-- actualizar incidente
create or replace procedure sp_actualizar_incidente(
    p_id bigint,
    p_estado varchar,
    p_observaciones text,
    p_fecha_cierre timestamptz default null
) as $$
begin
    update incidente
    set estado = p_estado,
        observaciones = p_observaciones,
        fecha_cierre = p_fecha_cierre,
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- eliminar incidente (soft delete - marcar como cerrado)
create or replace procedure sp_eliminar_incidente(p_id bigint) as $$
begin
    update incidente
    set estado = 'CERRADO',
        fecha_cierre = now(),
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- listar todo el historial
create or replace function sp_listar_historial_incidentes()
returns table (
    id bigint,
    incidente_id bigint,
    estado_anterior varchar,
    estado_nuevo varchar,
    comentario text,
    usuario_id bigint,
    nombre_usuario varchar,
    fecha timestamptz
) as $$
begin
    return query
    select h.id, h.incidente_id, h.estado_anterior, h.estado_nuevo,
           h.comentario, h.usuario_id, u.nombre as nombre_usuario, h.fecha
    from historial_incidente h
    left join usuario u on u.id = h.usuario_id
    order by h.id asc;
end;
$$ language plpgsql;

-- agregar entrada al historial
create or replace procedure sp_agregar_historial_incidente(
    p_incidente_id bigint,
    p_estado_nuevo varchar,
    p_estado_anterior varchar default null,
    p_comentario text default null,
    p_usuario_id bigint default null
) as $$
begin
    insert into historial_incidente (incidente_id, estado_anterior, estado_nuevo,
                                     comentario, usuario_id)
    values (p_incidente_id, p_estado_anterior, p_estado_nuevo,
            p_comentario, p_usuario_id);
end;
$$ language plpgsql;

-- buscar entrada de historial por id
create or replace function sp_buscar_historial_por_id(p_id bigint)
returns table (
    id bigint,
    incidente_id bigint,
    estado_anterior varchar,
    estado_nuevo varchar,
    comentario text,
    usuario_id bigint,
    fecha timestamptz
) as $$
begin
    return query
    select h.*
    from historial_incidente h
    where h.id = p_id;
end;
$$ language plpgsql;

-- actualizar comentario de una entrada del historial
create or replace procedure sp_actualizar_historial_incidente(
    p_id bigint,
    p_comentario text
) as $$
begin
    update historial_incidente
    set comentario = p_comentario
    where id = p_id;
end;
$$ language plpgsql;

-- eliminar entrada del historial
create or replace procedure sp_eliminar_historial_incidente(p_id bigint) as $$
begin
    delete from historial_incidente
    where id = p_id;
end;
$$ language plpgsql;
